FROM mysql:latest

# Définit les variables d'environnement
ENV MYSQL_HOST=mysql
ENV MYSQL_DATABASE=zoo
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_USER=test
ENV MYSQL_PASSWORD=test
ENV MYSQL_TYPE=mysql
ENV MYSQL_PORT=3307

EXPOSE 3306

CMD ["mysqld"]
